[package]
name = "teepee"
version = "0.1.0"
authors = ["Vojtech Kral <vojtech@kral.hk>"]

[dependencies]
glib = "^0"
glib-sys = "^0"
gio = "^0"
gtk = "^0"
cairo-rs = "^0"
tp-lib = { path = "ws/tp-lib" }

[workspace]
members = [
	"ws/tp-pty",
	"ws/tp-term",
	"ws/tp-lib",
]
