[package]
name = "tp-term"
version = "0.1.0"
authors = ["Vojtech Kral <vojtech@kral.hk>"]

[dependencies]
bitflags = "1.0"
smallvec = "0.6"
# unicode-normalization = "0.1"
unicode-width = "0.1"
error-chain = "0.11"
